//! Socket communication server
//!
//! Listen on Unix Domain Socket, receive and handle client requests.

use std::{
    fs::{self, File},
    io::Read,
    os::unix::{
        fs::PermissionsExt,
        net::{UnixListener, UnixStream},
    },
    path::Path,
};

use nix::unistd::User;

use crate::{
    constants::SOCKET_PATH,
    daemon::process::kill_process,
    db::DbPool,
    hardware::GpuPool,
    macros::{green, red},
    types::{DeleteTarget, Job, JobPrintInfo, JobRequest, JobStatus, Request, Response},
};

/// Server handling client requests via Unix Domain Socket
///
/// Owns handles to shared database and GPU pool, dispatches incoming
/// requests to appropriate handlers.
pub struct Server {
    /// Database connection pool for job persistence
    queue: DbPool,
    /// GPU pool for resource allocation tracking
    gpu_pool: GpuPool,
}

impl Server {
    /// Create a new Server instance
    ///
    /// # Arguments
    ///
    /// * `queue` - Database connection pool for job CRUD operations
    /// * `gpu_pool` - GPU pool for tracking GPU allocation state
    ///
    /// # Returns
    ///
    /// A new Server instance ready to run and handle requests
    pub fn new(queue: DbPool, gpu_pool: GpuPool) -> Self {
        Self { queue, gpu_pool }
    }

    /// Start the server and listen for incoming connections
    ///
    /// Creates Unix Domain Socket at SOCKET_PATH, removes stale socket file
    /// if exists. Enter main event loop accepting client connections.
    pub fn run(&self) {
        // Ensure old socket file is removed
        let socket_path = Path::new(SOCKET_PATH);
        if socket_path.exists() {
            fs::remove_file(socket_path).unwrap();
        }

        // Bind Unix Domain Socket
        let listener = UnixListener::bind(socket_path).unwrap();
        fs::set_permissions(socket_path, PermissionsExt::from_mode(0o666)).ok();
        println!("{}", green!("Daemon listening on {}", SOCKET_PATH));

        // Loop accepting client connections
        for stream in listener.incoming() {
            match stream {
                Ok(stream) => self.handle_connection(stream),
                Err(err) => eprintln!("{}", red!("{}", err)),
            }
        }
    }

    /// Process a single client connection
    ///
    /// Reads JSON request from client, dispatches to handler, writes response.
    ///
    /// # Arguments
    ///
    /// * `stream` - Unix stream connected to client
    fn handle_connection(&self, mut stream: UnixStream) {
        // Read client request
        let mut buffer = String::new();
        if let Err(e) = stream.read_to_string(&mut buffer) {
            eprintln!("{}", red!("Failed to read request: {}", e));
            return;
        }

        // Parse and handle request
        let response = match serde_json::from_str::<Request>(&buffer) {
            Ok(req) => {
                println!("{}", green!("Received request: {:?}", req));
                self.dispatch(req)
            }
            Err(e) => Response::Error {
                message: format!("Failed to parse request: {}", e),
            },
        };

        // Write response back to client
        if let Err(e) = serde_json::to_writer(&stream, &response) {
            eprintln!("{}", red!("Failed to write response: {}", e));
        }
    }

    /// Route request to appropriate handler based on request type
    ///
    /// # Arguments
    ///
    /// * `req` - Parsed Request enum variant
    ///
    /// # Returns
    ///
    /// Response generated by the corresponding handler function
    fn dispatch(&self, req: Request) -> Response {
        match req {
            Request::StopCheck => self.handle_stop_check(),
            Request::Submit { job } => self.handle_submit(job),
            Request::Cancel {
                id,
                username,
                force,
            } => self.handle_cancel(id, &username, force),
            Request::Delete { target } => self.handle_delete(target),
            Request::Status => self.handle_status(),
            Request::List { username, limit } => self.handle_list(&username, limit),
            Request::Log { id, username } => self.handle_log(id, &username),
        }
    }

    /// Handle stop check request
    ///
    /// # Returns
    ///
    /// Count of currently running jobs to determine if safe to stop.
    fn handle_stop_check(&self) -> Response {
        let running = self
            .queue
            .lock()
            .unwrap()
            .get_jobs_by_status(JobStatus::Running)
            .unwrap_or_default();

        Response::StopCheck {
            running_count: running.len(),
        }
    }

    /// Handle job submission request
    ///
    /// Assigns new job ID, inserts into database, returns job ID and log path.
    ///
    /// # Arguments
    ///
    /// * `req` - Job request containing command, GPU count, environment, etc.
    ///
    /// # Returns
    ///
    /// Response containing assigned job ID and log file path, or error message on failure.
    fn handle_submit(&self, req: JobRequest) -> Response {
        let q = self.queue.lock().unwrap();
        let job = Job::from_request(q.get_max_id().unwrap_or(0) + 1, req);

        if let Err(e) = self.prepare_log_file(&job.log_path, &job.username) {
            return Response::Error { message: e };
        }

        match q.insert_job(&job) {
            Ok(_) => Response::Submit {
                id: job.id,
                log_path: job.log_path.clone(),
            },
            Err(e) => Response::Error {
                message: e.to_string(),
            },
        }
    }

    /// Prepare log file for a new job
    ///
    /// Creates log file and parent directories if needed, sets ownership to job user.
    ///
    /// # Arguments
    ///
    /// * `log_file` - Path to the log file to prepare
    /// * `username` - Username to set as owner of the log file
    ///
    /// # Returns
    ///
    /// `Ok(())` if log file is prepared successfully, `Err` with error message on failure
    fn prepare_log_file(&self, log_file: &str, username: &str) -> Result<(), String> {
        let log = Path::new(log_file);
        let parent = log
            .parent()
            .ok_or_else(|| format!("Invalid log path: {}", log_file))?;

        fs::create_dir_all(parent).map_err(|e| format!("Failed to create log dir: {}", e))?;
        File::options()
            .create(true)
            .append(true)
            .open(log)
            .map_err(|e| format!("Failed to prepare log file: {}", e))?;

        let user = User::from_name(username)
            .map_err(|e| format!("Failed to query user '{}': {}", username, e))?
            .ok_or_else(|| format!("User not found: {}", username))?;

        nix::unistd::chown(log, Some(user.uid), Some(user.gid))
            .map_err(|e| format!("Failed to chown log file '{}': {}", log_file, e))?;

        Ok(())
    }

    /// Handle job cancellation request
    ///
    /// Checks permission and job status. Pending jobs are directly cancelled.
    ///
    /// Running jobs require `--force` flag and will be forcibly terminated.
    ///
    /// # Arguments
    ///
    /// * `id` - Job ID to cancel
    /// * `username` - User requesting cancellation
    /// * `force` - Whether to forcibly terminate running jobs
    ///
    /// # Returns
    ///
    /// Response indicating success or failure of cancellation request, or error message on failure.
    fn handle_cancel(&self, id: usize, username: &str, force: bool) -> Response {
        match self.get_job_with_permission(id, username) {
            Ok(job) => match job.status {
                JobStatus::Pending => {
                    self.queue
                        .lock()
                        .unwrap()
                        .update_status(id, JobStatus::Cancelled)
                        .ok();
                    Response::Cancel
                }
                JobStatus::Running if force => self.force_cancel_running(id),
                JobStatus::Running => Response::Error {
                    message: "Job is running, requires --force".to_string(),
                },
                _ => Response::Error {
                    message: "Job has ended, cannot cancel".to_string(),
                },
            },
            Err(resp) => resp,
        }
    }

    /// Force terminate a running job process
    ///
    /// Sends SIGTERM to process, releases allocated GPUs, updates job status.
    ///
    /// # Arguments
    ///
    /// * `id` - Job ID to terminate
    ///
    /// # Returns
    ///
    /// Response indicating success of cancellation or error message on failure
    fn force_cancel_running(&self, id: usize) -> Response {
        let pid = self.gpu_pool.lock().unwrap().get_first_pid_by_job_id(id);
        if let Some(pid) = pid
            && let Err(e) = kill_process(pid)
        {
            eprintln!("{}", red!("Failed to kill process: {}", e));
            Response::Error {
                message: "Failed to kill process".to_string(),
            }
        } else {
            self.queue
                .lock()
                .unwrap()
                .update_status(id, JobStatus::Cancelled)
                .ok();
            let gpus_to_release = self
                .gpu_pool
                .lock()
                .unwrap()
                .get_all_status()
                .iter()
                .filter(|g| g.job_id == Some(id))
                .map(|g| g.id)
                .collect::<Vec<_>>();
            self.gpu_pool
                .lock()
                .unwrap()
                .release_batch(&gpus_to_release);

            Response::Cancel
        }
    }

    /// Handle job deletion request
    ///
    /// Only completed, failed, or cancelled jobs can be deleted.
    /// Pending and running jobs cannot be deleted.
    ///
    /// # Arguments
    ///
    /// * `id` - Job ID to delete
    ///
    /// # Returns
    ///
    /// Response indicating number of jobs deleted or error message on failure
    fn handle_delete(&self, target: DeleteTarget) -> Response {
        let result = match target {
            DeleteTarget::Single(id) => self.delete_single(id),
            DeleteTarget::ByStatuses(statuses) => self.delete_by_statuses(statuses),
            DeleteTarget::AllTerminated => self.delete_all_terminated(),
        }
        .and_then(|ids| {
            self.queue
                .lock()
                .unwrap()
                .delete_jobs(&ids)
                .map_err(|e| e.to_string())
        });

        match result {
            Ok(count) => Response::Delete { count },
            Err(e) => Response::Error { message: e },
        }
    }

    /// Delete a single job by ID after checking its status
    ///
    /// Only allows deletion of jobs that are completed, failed, or cancelled.
    ///
    /// # Arguments
    ///
    /// * `id` - Job ID to delete
    ///
    /// # Returns
    ///
    /// `Ok(vec![id])` if the job can be deleted, `Err` with error message if not found or not in deletable status
    fn delete_single(&self, id: usize) -> Result<Vec<usize>, String> {
        let q = self.queue.lock().unwrap();
        match q.get_job_by_id(id) {
            Ok(Some(job)) => {
                if !matches!(
                    job.status,
                    JobStatus::Completed | JobStatus::Failed | JobStatus::Cancelled
                ) {
                    return Err(format!(
                        "Job {} is {}, cannot delete",
                        id,
                        job.status.as_str()
                    ));
                }

                Ok(vec![id])
            }
            Ok(None) => Err(format!("Failed to find job {}", id)),
            Err(e) => Err(format!("Failed to query job: {}", e)),
        }
    }

    /// Delete jobs by their statuses
    ///
    /// Only allows deletion of jobs that are completed, failed, or cancelled.
    ///
    /// # Arguments
    ///
    /// * `statuses` - List of job statuses to delete
    ///
    /// # Returns
    ///
    /// `Ok(vec![ids])` if jobs can be deleted, `Err` with error message if any status is not deletable or query fails
    fn delete_by_statuses(&self, statuses: Vec<JobStatus>) -> Result<Vec<usize>, String> {
        let allowed = |s: &JobStatus| {
            matches!(
                s,
                JobStatus::Completed | JobStatus::Failed | JobStatus::Cancelled
            )
        };
        if !statuses.iter().all(allowed) {
            return Err("Only completed, failed, cancelled statuses are allowed".to_string());
        }

        let q = self.queue.lock().unwrap();
        q.get_jobs_by_statuses(&statuses)
            .map(|jobs| jobs.into_iter().map(|j| j.id).collect())
            .map_err(|e| format!("Failed to query jobs: {}", e))
    }

    /// Delete all jobs that are in terminated states (completed, failed, cancelled)
    ///
    /// # Returns
    ///
    /// `Ok(vec![ids])` if jobs can be deleted, `Err` with error message if query fails
    fn delete_all_terminated(&self) -> Result<Vec<usize>, String> {
        let q = self.queue.lock().unwrap();
        let statuses = vec![
            JobStatus::Completed,
            JobStatus::Failed,
            JobStatus::Cancelled,
        ];
        q.get_jobs_by_statuses(&statuses)
            .map(|jobs| jobs.into_iter().map(|j| j.id).collect())
            .map_err(|e| format!("Failed to query jobs: {}", e))
    }

    /// Handle GPU status query request
    ///
    /// # Returns
    ///
    /// Response containing list of all GPUs with their current status
    fn handle_status(&self) -> Response {
        let gpus = self.gpu_pool.lock().unwrap().get_all_status();
        Response::Status { gpus }
    }

    /// Handle job list request
    ///
    /// # Arguments
    ///
    /// * `username` - Filter jobs by this user (root sees all)
    /// * `limit` - Limit number of jobs returned, None for all
    ///
    /// # Returns
    ///
    /// Jobs filtered by username. Root user sees all jobs.
    fn handle_list(&self, username: &str, limit: Option<usize>) -> Response {
        let (total, jobs) = {
            let q = self.queue.lock().unwrap();

            let total = q.get_job_count().unwrap_or(0) as usize;
            let jobs = if username == "root" {
                q.get_all_jobs(limit).unwrap_or_default()
            } else {
                q.get_jobs_by_username(username, limit).unwrap_or_default()
            };

            (total, jobs)
        };

        let job_infos: Vec<JobPrintInfo> = jobs
            .into_iter()
            .map(|j| JobPrintInfo {
                id: j.id,
                status: j.status,
                username: j.username,
                command: j.command,
                gpus: j.gpus,
                start_time: j.start_time,
                end_time: j.end_time,
            })
            .collect();

        Response::List {
            jobs: job_infos,
            total,
        }
    }

    /// Handle job log path request
    ///
    /// # Arguments
    ///
    /// * `id` - Job ID
    /// * `username` - User requesting log path
    ///
    /// # Returns
    ///
    /// Log file path for specified job after permission check.
    fn handle_log(&self, id: usize, username: &str) -> Response {
        match self.get_job_with_permission(id, username) {
            Ok(job) => Response::Log {
                log_path: job.log_path,
            },
            Err(resp) => resp,
        }
    }

    /// Fetch job and verify user permission
    ///
    /// # Arguments
    ///
    /// * `id` - Job ID to fetch
    /// * `username` - User requesting the job
    ///
    /// # Returns
    ///
    /// Job if found and user has permission (root or job owner).
    fn get_job_with_permission(&self, id: usize, username: &str) -> Result<Job, Response> {
        match self.queue.lock().unwrap().get_job_by_id(id) {
            Ok(Some(job)) => {
                if username != "root" && username != job.username {
                    Err(Response::Error {
                        message: format!(
                            "Permission denied: job {} belongs to user '{}'",
                            id, job.username
                        ),
                    })
                } else {
                    Ok(job)
                }
            }
            Ok(None) => Err(Response::Error {
                message: format!("Job {} not found", id),
            }),
            Err(e) => Err(Response::Error {
                message: format!("Database error: {}", e),
            }),
        }
    }
}

/// Check if daemon is running
///
/// Determines by attempting to connect to socket.
///
/// # Returns
///
/// True if daemon is running (socket connection successful), false otherwise.
pub fn is_daemon_running() -> bool {
    UnixStream::connect(SOCKET_PATH).is_ok()
}
